### ISSUE TITLE
How is WG setup?

### ISSUE THREAD

**Issue by jungle-boogie** [fazalmajid/edgewalker#2]
Hello,

How exactly is wireguard setup in the script?

I don't see a wg0 interface, or a tun0, setup for wiregaurd. I see a few instances in the script for wireguard but nothing really establishing a wireguard tunnel.

What am I missing?

**Comment by fazalmajid** [comment]
It’s not set up yet, work in progress...

**Comment by fazalmajid** [comment]
OK, so I added a first draft of WireGuard support and verified it works using the official iOS and Android WG clients.

It has the following limitations:
* only one client is supported at the moment. I will modify the script to generate multiple client conf files and corresponding QR codes, and instead of displaying two QR codes at the end, only one that points to a web page that allows choosing which of the N client keys you want (or IPsec)
* the WireGuard clients use CloudFlare's DNS for now, which is not ideal from a privacy perspective (I will modify the script to turn on the unbound DNS server on the OpenBSD machine and use that instead).

**Comment by jungle-boogie** [comment]
Excellent news! Thank you for your progress, it’s truly appreciated.

**Comment by fazalmajid** [comment]
I now generate 32 configs for WireGuard and a summary page with all of them.

**Comment by fazalmajid** [comment]
I also added unbound for DNS lookups instead of CloudFlare
